version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: dora
      MYSQL_USER: frank
      MYSQL_PASSWORD: frank123
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
