spring:
  application:
    name: dora

  graphql:
    graphiql:
      enabled: true
      path: /graphiql
    path: /graphql

  datasource:
    url: jdbc:mysql://localhost:3306/dora?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    username: root
    password: admin123
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    elasticsearch:
      repositories:
        enabled: true


logging:
  level:
    org:
      springframework:
        graphql: DEBUG
        boot:
          autoconfigure:
            graphql: DEBUG

        data:
          elasticsearch: DEBUG

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0

deepseek:
  api:
    key: sk-b73105e1311b46b5b104b5c49d0aa6b6